### ISSUE TITLE
Guidance

### ISSUE THREAD

**Issue by BasharAG** [RInvestments/sun-dance#1]
Checked your code out, and I have to say I am very impressed. Are you planning on adding an installation guide (dependencies, etc.)? Are these python executables meant to be used individually?

**Comment by mpkuse** [comment]
Thanks for the support. Actually there are 3 scripts (inserter, retriever and parser). I agree it is not exactly straight forward to get it working on your system. I will put up the dependencies list.

Possibly a GUI interface as well. But my prime focus is to provide command line utilities . 

Anyways do keep a watch on this project if you are into stuff like this. Suggestions are welcome as well

**Comment by mpkuse** [comment]
Just as a heads up, I made it a lot easier to set up. Do try it out if you are interested!
